allow to set username distinct from file owner (user)
johanfleury/puppet-unbound pull request #10
Opened 2019-10-26 15:22 UTC by trefzer

the default value (unbound) is kept the same for both.

2019-10-27 04:12 UTC, johanfleury commented
Hi @trefzer, thank you for the PR.

I'll have a look at it as soon as possible (I didn't write tests for this module, but I still need to check that everything's ok before merging).

Also, could you tell me what's the use case is for that change?

2019-10-27 08:46 UTC, trefzer commented
I'm switching to Debian 10 (buster), unbound 1.9.0.
There I needed to set the owner of the configuration files to root (group unbound), to start
unbound as user unbound (with usermod). Otherwise I got a permission denied ! (yes true, It took me long to realize !).
This also makes sense from another point of vue: the owner of the process (unbound) is not allowed to write the config files owned by root. So it definitly makes sence to distinct.

2020-05-18 16:38 UTC, johanfleury requested changes
Hey @trefzer sorry for the delay and thank you for your patience.

So just to clarify, 'cause it took me a long time to understand what was going on, here what’s happening when unbound starts:

1. As many other daemon, Unbound starts as root.
2. It tries to read its configuration file `/etc/unbound/unbound.conf`: this fails with `EACESS` (permission denied) when the file is not explicitly readable by root.
3. It listen to sockets and ports.
4. It reads other files (such as TLS certificates, root anchors, etc.): : this fails with `EACESS` (permission denied) when the file is not explicitly readable by root or is outside `/etc/unbound`.
5. It then switch to the user defined by the `username` directive in the configuration (default is `unbound`).

The issue at point 2 is due to AppArmor dropping all capabilities but the ones that are needed for unbound to work properly. This includes removing the implicit `CAP_DAC_OVERRIDE` that allows `root` to access any files whatever their permissions are.

The issue at point 5 is not related to you PR but is also due to AppArmor. The AppArmor profile is limiting file access for unbound to `/etc/unbound` (and some few other directories, but that’s not a concern here).

---

That’s it for the clarification, now regarding the PR, could you please make `unbound::user` defaults to `root` and `unbound::username` defaults to `unbound`? The module is not usable on Debian Buster with the current default parameters.

2020-05-18 17:31 UTC, trefzer commented
Hi 
phew, long time ago, I have to go through in detail...
Just a call back/suggestion:
- I suggest using hiera for setting the defaults.
- I set all the 'old' defaults as they have been for debian 8 and 9 (these are the ones supported according to metadata.json)
- I set the Debian default for version 10 and onward according youre suggestion
- I add debian buster (10) to supported in metadata.json

2020-06-19 19:17 UTC, johanfleury commented
Hey @trefzer, I’m sorry for keeping you waiting all this time.

So, I did a few thing in the last couple of hours:

* I moved the module to PDK so that it’s easier to run tests and syntax checks.
* I fixed issues reported by puppet-lint and rubocop and updated the tests so that they run for all supported platform.
* As suggested I moved to hiera and in-module data for default parameters.
* And most importantly, I made root the owner of the configuration files and directories and fixed the tests accordingly.

The module has been updated to version `0.3.0` and uploaded on the forge.

I also [moved the repository to Gitlab](https://gitlab.com/marionetoj/puppet-modules/unbound) and I’ll make this one a mirror and archive it.

So I’m closing your PR, but I’d like to thank you for reporting the issue and for doing the initial work. Your help to improve this module is of course always welcome :)

2020-06-19 19:17 UTC, closed without merging